# For more information, please refer to https://aka.ms/vscode-docker-python
FROM python:3.8-slim

# Keeps Python from generating .pyc files in the container
ENV PYTHONDONTWRITEBYTECODE=1

# Turns off buffering for easier container logging
ENV PYTHONUNBUFFERED=1

# Install pip requirements
COPY dist/projectmlincvmediapipe-0.1.0-py3-none-any.whl .
RUN python -m pip install projectmlincvmediapipe-0.1.0-py3-none-any.whl
RUN python -m pip install streamlit

WORKDIR /app
COPY streamlitapp/app.py /app

# Creates a non-root user with an explicit UID and adds permission to access the /app folder
# For more info, please refer to https://aka.ms/vscode-docker-python-configure-containers
EXPOSE 8501

# During debugging, this entry point will be overridden. For more information, please refer to https://aka.ms/vscode-docker-python-debug
ENTRYPOINT ["streamlit", "run"]
CMD [ "app.py"]