name: Tests on Pull Request

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install -r requirements_dev.txt
    - name: Run tests
      run: |
        pytest
    - name: Run style checks
      run: |
        pre-commit install
        pre-commit run -a
